config/routes.rb
Rails.application.routes.draw do
  root :to => 'cars#index'
  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car

  def index
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    creation_message = "#{@car.year} #{@car.make} #{@car.model} created"
    if @car.save
      redirect_to :cars_path,
                  :notice => creation_message
    end
  end

  private
  def set_car
    @user = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit([:year, :make, :model, :price])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= form_for(@car) do |f| %>
  <p>
    <%= f.label :make %>
    <%= f.text_field :make %>
  </p>
  <p>
    <%= f.label :model %>
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :year %>
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>